name: tekartik_common_utils
version: 0.11.1
description: Common pure dart utilities (not io or browser dependant)
author: Alexandre Roux Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/common_utils.dart
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependencies:
  path: '>=1.8.0'
  logging: '>=1.0.0'
  pub_semver: '>=1.4.1'
  synchronized: '>=2.0.0'
  meta: '>=1.3.0'
  pedantic: '>=1.10.0'
dev_dependencies:
  dev_test: '>=0.15.0'
  test: '>=1.16.3'
  yaml:
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: null_safety
  build_runner: '>=1.11.5'
  build_test: '>=1.3.7'
  build_web_compilers: '>=2.16.4'
  process_run: '>=0.12.0'