name: tekartik_common_utils
version: 0.2.3
description: Common  pure dart utilities (not io or browser dependant)
author: Alexandre Roux Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/tekartik_common_utils.dart
dependencies:
  pub_semver: any
  func: any
  synchronized:
    git: git://github.com/tekartik/synchronized.dart
dev_dependencies:
  browser: any
  dev_test: any
  test: any
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart