name: tekartik_common_utils
version: 0.2.1
dependencies:
  pub_semver: any
  func: any
dev_dependencies:
  dev_test: any
  test: any
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart