name: tekartik_common_utils
version: 0.4.11
description: Common  pure dart utilities (not io or browser dependant)
author: Alexandre Roux Tekartik <alex@tekartik.com>
homepage: https://github.com/tekartik/common_utils.dart
environment:
  sdk: '>=1.21.0 <2.0.0'
dependencies:
  pub_semver: any
  func: any
  synchronized: any
dev_dependencies:
  browser: any
  dev_test: any
  test: any
  chrome_travis:
    git: git://github.com/tekartik/chrome_travis.dart