name: Run CI
on:
  push:
  schedule:
    - cron: '0 0 * * 0'  # every sunday at midnight

jobs:
  test:
    name: Test on ${{ matrix.os }} / ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: .
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dart-channel: [stable, beta, dev]
    steps:
      - uses: cedx/setup-dart@v2
          with:
            release-channel: ${{ matrix.dart-channel }}
      - uses: actions/checkout@v2
      - run: dart --version
      - run: dart pub get
      - run: dart run tool/run_ci.dart