name: Run CI
on:
  push:
  schedule:
    - cron: '0 0 * * 0'  # every sunday at midnight

jobs:
  test:
    name: Dart test on ${{ matrix.os }} / ${{ matrix.dart-channel }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: .
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dart-channel: [stable, beta, dev]
    steps:
      - name: Set up Dart
        uses: cedx/setup-dart@v2
        with:
          release-channel: ${{ matrix.dart-channel }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dart version
        run: dart --version
      - name: pub get
        run: dart pub get
      - name: run_ci
        run: dart run tool/run_ci.dart